# Generated by Django 6.0.5 on 2026-06-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount_left', models.IntegerField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, upload_to='products/')),
                ('leather_type', models.CharField(max_length=100)),
                ('in_stock', models.CharField(choices=[('in_stock', 'In stock'), ('available_for_production', 'Available for production'), ('not_available', 'Not available')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone'), ('telegram', 'Telegram'), ('email', 'Email')], max_length=10)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in-production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('returned', 'Returned'), ('closed', 'Closed')], max_length=30)),
                ('delivery_method', models.CharField(choices=[('yandex', 'Yandex delivery'), ('SDEK', 'SDEK delivery'), ('postal', 'Postal services'), ('ozon', 'Ozon delivery')], max_length=30)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='Custom_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in-production', 'In production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed'), ('returned', 'Returned'), ('closed', 'Closed')], max_length=30)),
                ('delivery_method', models.CharField(choices=[('yandex', 'Yandex delivery'), ('SDEK', 'SDEK delivery'), ('postal', 'Postal services'), ('ozon', 'Ozon delivery')], max_length=30)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('leather_type', models.CharField(max_length=100)),
                ('reference', models.URLField(blank=True)),
                ('reference_2', models.URLField(blank=True)),
                ('reference_3', models.URLField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
    ]
